#
# drivers/net/wireless/Makefile
#
# Makefile for the Linux Wireless network device drivers.
#

O_TARGET := r8187.o

obj-y	:= r8180_93cx6.o r8180_pm.o r8180_rtl8225.o r8180_rtl8225z2.o r8180_wx.o r8187_core.o

obj-m   := $(O_TARGET)
include $(TOPDIR)/Rules.make
