# File: drivers/codec/Makefile
#
# Makefile for the Linux multi-media mpeg codec device drivers.
#

obj-y           :=
obj-m           :=
obj-n           :=
obj-            :=

#O_TARGET := codec.o

# All of the (potential) objects that export symbols.
# This list comes from 'grep -l EXPORT_SYMBOL *.[hc]'.


subdir-$(CONFIG_VW2010) += vw2010

include $(TOPDIR)/Rules.make

