


obj-y           += nor_core.lib
obj-m           :=
obj-n           :=
obj-            :=

O_TARGET	:= nor.o

export-objs	:= 
list-multi	:= 

mod-subdirs	:= 
subdir-y	:=
subdir-m	:= 

subdir-$(CONFIG_FLASH_NOR) += export
obj-$(CONFIG_FLASH_NOR)	+= export/export.o



include $(TOPDIR)/Rules.make



